apiVersion: v1
kind: Pod
metadata:
  name: kv260-runtime
  labels:
    name: kv260
spec:
  containers:
  - name: kv260-runtime
    image: chriskewis/xmutil
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /opt
      name: video
    - mountPath: /tmp
      name: dfx
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
        myway5.com/cola: 1
      limits:
        memory: "128Mi"
        cpu: "500m"
        myway5.com/cola: 1
    command: ["/bin/bash", "-ce", "tail -f /dev/null"]

  nodeSelector: 
    id: worker
  volumes:
  - name: video
    hostPath:
      path: /opt
      type: Directory
  - name: dfx
    hostPath:
      path: /tmp
      type: Directory
