apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cola
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: cola
    app.kubernetes.io/name: cola
    app.kubernetes.io/version: arm64
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: cola
      app.kubernetes.io/name: cola
  template:
    metadata:
      # This annotation is deprecated. Kept here for backward compatibility
      # See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        app.kubernetes.io/instance: cola
        app.kubernetes.io/name: cola
    spec:
      imagePullSecrets: []
      serviceAccountName: cola-admin
      securityContext: {}
      containers:
        - name: cola
          securityContext: {}
          image: "chriskewis/kv260-device-plugin:1103"
          imagePullPolicy: IfNotPresent
          resources: {}
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: devices
              mountPath: /etc/colas
      nodeSelector:
        cola-device: enable
      affinity: {}
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: myway5.com/cola
        operator: Exists
        effect: NoSchedule
      # Mark this pod as a critical add-on; when enabled, the critical add-on
      # scheduler reserves resources for critical add-on pods so that they can
      # be rescheduled after a failure.
      # See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
      priorityClassName: "system-node-critical"
      hostPID: true
      volumes:
      - name: device-plugin
        hostPath:
          type: Directory
          path: /var/lib/kubelet/device-plugins
      - name: devices
        hostPath:
          type: Directory
          path: /etc/colas
