apiVersion: v1
kind: ServiceAccount
metadata:
  name: cola-admin
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: cola
    app.kubernetes.io/name: cola
    app.kubernetes.io/version: arm64
